version: '3'

services:
  mt5:
    build: .
    image: gmag11/metatrader5_vnc
    container_name: mt5
    volumes:
      - ./data:/data
    ports:
      - 3000:3000
    environment:
      - UID=1000
      - GID=1000
      - CUSTOM_USER=username
      - PASSWORD=supersecure