version: '3'

services:
  mt5:
    build: .
    image: metatrader5:latest
    container_name: metatrader5
    hostname: metatrader5
    volumes:
      - ./data:/data
    ports:
      - 3000:3000
    environment:
      - UID=1000
      - GID=1000
      - CUSTOM_USER=username
      - PASSWORD=supersecure